In [9]:
import numpy as np
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [8]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.percentile(a,75))
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))

45
5.0
5.0
2.581988897471611
6.666666666666667
1
9
7.0
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]


In [13]:
# array manipulation
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.concatenate([a,b]))
print(np.vstack([a,b]))
print(np.hstack([a,b]))
print(np.stack([a,b],axis=0))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [33]:
a = np.arange(9)
print(a)
np.split(a, 3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [25]:
a=np.array([1,2,3])
print(a)
b=np.append(a,[4,5])
print(b)
c=np.insert(a,1,99)
print(a)
print(c)


[1 2 3]
[1 2 3 4 5]
[1 2 3]
[ 1 99  2  3]


In [26]:
a=np.array([3,1,4,5,7,9,8,2])
print(a)
b=np.sort(a)      #sort
print(b)

[3 1 4 5 7 9 8 2]
[1 2 3 4 5 7 8 9]


In [29]:
a=np.array([3,1,4,5,7,9,8,2,2,2])
print(a)
print(np.unique(a))
print(a)
b=a[::-1]      #reverse
print(b)

[3 1 4 5 7 9 8 2 2 2]
[1 2 3 4 5 7 8 9]
[3 1 4 5 7 9 8 2 2 2]
[2 2 2 8 9 7 5 4 1 3]


In [34]:
#broadcating -> operation on different ndim
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
row_add = np.array([10,20,30])
print(matrix+row_add)

[[1 2 3]
 [4 5 6]]
[[11 22 33]
 [14 25 36]]
